### ISSUE TITLE
Still works in 2022?

### ISSUE THREAD

**Issue by tbarnes4** [simmeringratchet/LDSGeneralConferenceDownloader#4]
I was using the latest branch (LDSGeneralConferenceDownloader-0732128c4ca9a4498469336ecf70a9e931706fe4/), and I am coming across a problem where from what I can tell nothing is being pulled and so is causing an out of range error.  See below:

> % python3.9 gen_conf_downloader.py -start 2021 -end 2022 -dest ../talks/ -nocleanup -verbose -lang eng
https://www.churchofjesuschrist.org/languages
https://www.churchofjesuschrist.org/general-conference/conferences?lang=eng
Traceback (most recent call last):
  File "[source_dir]/gen_conf_downloader.py", line 435, in <module>
    get_all_conferences_seasons(cli_args)
  File "[source_dir]/gen_conf_downloader.py", line 72, in get_all_conferences_seasons
    remove_generated_files(args, playlist_dirs)
  File "[source_dir]/gen_conf_downloader.py", line 200, in remove_generated_files
    shutil.rmtree(f'{get_output_dir(args)}/{playlist_dirs[CONFERENCES_DIR]}', ignore_errors=True)
IndexError: list index out of range

Does this script still work with the current website?

**Comment by snow-jallen** [comment]
Looks like a fantastic tool.  Any chance of this getting some love to update to the latest URL structure?

**Comment by snow-jallen** [comment]
Found it: https://github.com/GatorQue/LDSGeneralConferenceDownloader
